name = "EasyModelAnalysis"
uuid = "ef4b24a4-a090-4686-a932-e7e56a5a83bd"
authors = ["SciML"]
version = "0.1.10"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GlobalSensitivity = "af5da776-676b-467e-8baf-acd8249e4f0f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationBBO = "3e6eede4-6085-4f62-9a71-46d9bc1eb92b"
OptimizationMOI = "fd9f6733-72f4-499f-8506-86b2bdd0dea1"
OptimizationNLopt = "4e6fcdb7-1186-4e1f-a706-475e75c168bb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SciMLExpectations = "afe9f18d-7609-4d0e-b7b7-af0cb72b8ea8"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
DifferentialEquations = "7"
Distributions = "0.25"
GlobalSensitivity = "2"
ModelingToolkit = "8"
NLopt = "0.6"
Optimization = "3"
OptimizationBBO = "0.1"
OptimizationMOI = "0.1"
OptimizationNLopt = "0.1"
Plots = "1"
Reexport = "1"
SciMLBase = "1"
SciMLExpectations = "2"
Turing = "0.22, 0.23, 0.24"
julia = "1.6"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SafeTestsets", "Test"]
