[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
EasyModelAnalysis = "ef4b24a4-a090-4686-a932-e7e56a5a83bd"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
DifferentialEquations = "7"
ModelingToolkit = "8"
Documenter = "0.27"
EasyModelAnalysis = "0.0.1"
Plots = "1"
