[deps]
AlgebraicPetri = "4f99eebe-17bf-4e98-b6a1-2c4f205a959b"
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
EasyModelAnalysis = "ef4b24a4-a090-4686-a932-e7e56a5a83bd"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationMOI = "fd9f6733-72f4-499f-8506-86b2bdd0dea1"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SBMLToolkit = "86080e66-c8ac-44c2-a1a0-9adaadfe4a4e"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
AlgebraicPetri = "0.8.2"
Catlab = "0.14"
DifferentialEquations = "7"
Documenter = "1"
EasyModelAnalysis = "0.1, 1"
Ipopt = "1"
ModelingToolkit = "9"
NLopt = "0.6, 1"
Optimization = "3"
OptimizationMOI = "0.4"
Plots = "1"
SBMLToolkit = "0.1"
UnPack = "1"
